#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.MessageBroadcast.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iProject")]
	public partial class iProjectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSub_System(Sub_System instance);
    partial void UpdateSub_System(Sub_System instance);
    partial void DeleteSub_System(Sub_System instance);
    partial void InsertSms_Message_Box(Sms_Message_Box instance);
    partial void UpdateSms_Message_Box(Sms_Message_Box instance);
    partial void DeleteSms_Message_Box(Sms_Message_Box instance);
    partial void InsertMessage_Broad_Setting(Message_Broad_Setting instance);
    partial void UpdateMessage_Broad_Setting(Message_Broad_Setting instance);
    partial void DeleteMessage_Broad_Setting(Message_Broad_Setting instance);
    #endregion
		
		public iProjectDataContext() : 
				base(global::System.MessageBroadcast.Properties.Settings.Default.iProjectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public iProjectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iProjectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iProjectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iProjectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sub_System> Sub_Systems
		{
			get
			{
				return this.GetTable<Sub_System>();
			}
		}
		
		public System.Data.Linq.Table<D_LNTP> D_LNTPs
		{
			get
			{
				return this.GetTable<D_LNTP>();
			}
		}
		
		public System.Data.Linq.Table<D_MGTP> D_MGTPs
		{
			get
			{
				return this.GetTable<D_MGTP>();
			}
		}
		
		public System.Data.Linq.Table<D_MSG> D_MSGs
		{
			get
			{
				return this.GetTable<D_MSG>();
			}
		}
		
		public System.Data.Linq.Table<Sms_Message_Box> Sms_Message_Boxes
		{
			get
			{
				return this.GetTable<Sms_Message_Box>();
			}
		}
		
		public System.Data.Linq.Table<Message_Broad_Setting> Message_Broad_Settings
		{
			get
			{
				return this.GetTable<Message_Broad_Setting>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Msgb.PrepareSendCustSms")]
		public ISingleResult<PrepareSendCustSmsResult> PrepareSendCustSms([global::System.Data.Linq.Mapping.ParameterAttribute(Name="X", DbType="Xml")] System.Xml.Linq.XElement x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), x);
			return ((ISingleResult<PrepareSendCustSmsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_CRNTUSER_U", IsComposable=true)]
		public string GET_CRNTUSER_U([global::System.Data.Linq.Mapping.ParameterAttribute(Name="X", DbType="Xml")] System.Xml.Linq.XElement x)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), x).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="DataGuard.Sub_System")]
	public partial class Sub_System : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SUB_SYS;
		
		private string _DESC;
		
		private string _SCHM_NAME;
		
		private EntitySet<Sms_Message_Box> _Sms_Message_Boxes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSUB_SYSChanging(int value);
    partial void OnSUB_SYSChanged();
    partial void OnDESCChanging(string value);
    partial void OnDESCChanged();
    partial void OnSCHM_NAMEChanging(string value);
    partial void OnSCHM_NAMEChanged();
    #endregion
		
		public Sub_System()
		{
			this._Sms_Message_Boxes = new EntitySet<Sms_Message_Box>(new Action<Sms_Message_Box>(this.attach_Sms_Message_Boxes), new Action<Sms_Message_Box>(this.detach_Sms_Message_Boxes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_SYS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SUB_SYS
		{
			get
			{
				return this._SUB_SYS;
			}
			set
			{
				if ((this._SUB_SYS != value))
				{
					this.OnSUB_SYSChanging(value);
					this.SendPropertyChanging();
					this._SUB_SYS = value;
					this.SendPropertyChanged("SUB_SYS");
					this.OnSUB_SYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DESC]", Storage="_DESC", DbType="NVarChar(100)")]
		public string DESC
		{
			get
			{
				return this._DESC;
			}
			set
			{
				if ((this._DESC != value))
				{
					this.OnDESCChanging(value);
					this.SendPropertyChanging();
					this._DESC = value;
					this.SendPropertyChanged("DESC");
					this.OnDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHM_NAME", DbType="VarChar(30)")]
		public string SCHM_NAME
		{
			get
			{
				return this._SCHM_NAME;
			}
			set
			{
				if ((this._SCHM_NAME != value))
				{
					this.OnSCHM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SCHM_NAME = value;
					this.SendPropertyChanged("SCHM_NAME");
					this.OnSCHM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sub_System_Sms_Message_Box", Storage="_Sms_Message_Boxes", ThisKey="SUB_SYS", OtherKey="SUB_SYS")]
		public EntitySet<Sms_Message_Box> Sms_Message_Boxes
		{
			get
			{
				return this._Sms_Message_Boxes;
			}
			set
			{
				this._Sms_Message_Boxes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sms_Message_Boxes(Sms_Message_Box entity)
		{
			this.SendPropertyChanging();
			entity.Sub_System = this;
		}
		
		private void detach_Sms_Message_Boxes(Sms_Message_Box entity)
		{
			this.SendPropertyChanging();
			entity.Sub_System = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="DataGuard.D$LNTP")]
	public partial class D_LNTP
	{
		
		private string _VALU;
		
		private string _DOMN_DESC;
		
		public D_LNTP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALU", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string VALU
		{
			get
			{
				return this._VALU;
			}
			set
			{
				if ((this._VALU != value))
				{
					this._VALU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMN_DESC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DOMN_DESC
		{
			get
			{
				return this._DOMN_DESC;
			}
			set
			{
				if ((this._DOMN_DESC != value))
				{
					this._DOMN_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="DataGuard.D$MGTP")]
	public partial class D_MGTP
	{
		
		private string _VALU;
		
		private string _DOMN_DESC;
		
		public D_MGTP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALU", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string VALU
		{
			get
			{
				return this._VALU;
			}
			set
			{
				if ((this._VALU != value))
				{
					this._VALU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMN_DESC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DOMN_DESC
		{
			get
			{
				return this._DOMN_DESC;
			}
			set
			{
				if ((this._DOMN_DESC != value))
				{
					this._DOMN_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="DataGuard.D$MSGS")]
	public partial class D_MSG
	{
		
		private string _VALU;
		
		private string _DOMN_DESC;
		
		public D_MSG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALU", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string VALU
		{
			get
			{
				return this._VALU;
			}
			set
			{
				if ((this._VALU != value))
				{
					this._VALU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMN_DESC", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DOMN_DESC
		{
			get
			{
				return this._DOMN_DESC;
			}
			set
			{
				if ((this._DOMN_DESC != value))
				{
					this._DOMN_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Msgb.Sms_Message_Box")]
	public partial class Sms_Message_Box : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MBID;
		
		private System.Nullable<int> _SUB_SYS;
		
		private string _LINE_TYPE;
		
		private System.Nullable<System.DateTime> _ACTN_DATE;
		
		private System.Nullable<long> _RFID;
		
		private string _PHON_NUMB;
		
		private string _MSGB_TEXT;
		
		private string _MSGB_TYPE;
		
		private string _STAT;
		
		private string _MESG_ID;
		
		private string _EROR_CODE;
		
		private string _EROR_MESG;
		
		private System.Nullable<System.DateTime> _SRVR_SEND_DATE;
		
		private System.Nullable<int> _MESG_LENT;
		
		private string _CRET_BY;
		
		private System.Nullable<System.DateTime> _CRET_DATE;
		
		private string _MDFY_BY;
		
		private System.Nullable<System.DateTime> _MDFY_DATE;
		
		private EntityRef<Sub_System> _Sub_System;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMBIDChanging(long value);
    partial void OnMBIDChanged();
    partial void OnSUB_SYSChanging(System.Nullable<int> value);
    partial void OnSUB_SYSChanged();
    partial void OnLINE_TYPEChanging(string value);
    partial void OnLINE_TYPEChanged();
    partial void OnACTN_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnACTN_DATEChanged();
    partial void OnRFIDChanging(System.Nullable<long> value);
    partial void OnRFIDChanged();
    partial void OnPHON_NUMBChanging(string value);
    partial void OnPHON_NUMBChanged();
    partial void OnMSGB_TEXTChanging(string value);
    partial void OnMSGB_TEXTChanged();
    partial void OnMSGB_TYPEChanging(string value);
    partial void OnMSGB_TYPEChanged();
    partial void OnSTATChanging(string value);
    partial void OnSTATChanged();
    partial void OnMESG_IDChanging(string value);
    partial void OnMESG_IDChanged();
    partial void OnEROR_CODEChanging(string value);
    partial void OnEROR_CODEChanged();
    partial void OnEROR_MESGChanging(string value);
    partial void OnEROR_MESGChanged();
    partial void OnSRVR_SEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSRVR_SEND_DATEChanged();
    partial void OnMESG_LENTChanging(System.Nullable<int> value);
    partial void OnMESG_LENTChanged();
    partial void OnCRET_BYChanging(string value);
    partial void OnCRET_BYChanged();
    partial void OnCRET_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCRET_DATEChanged();
    partial void OnMDFY_BYChanging(string value);
    partial void OnMDFY_BYChanged();
    partial void OnMDFY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMDFY_DATEChanged();
    #endregion
		
		public Sms_Message_Box()
		{
			this._Sub_System = default(EntityRef<Sub_System>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MBID
		{
			get
			{
				return this._MBID;
			}
			set
			{
				if ((this._MBID != value))
				{
					this.OnMBIDChanging(value);
					this.SendPropertyChanging();
					this._MBID = value;
					this.SendPropertyChanged("MBID");
					this.OnMBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_SYS", DbType="Int")]
		public System.Nullable<int> SUB_SYS
		{
			get
			{
				return this._SUB_SYS;
			}
			set
			{
				if ((this._SUB_SYS != value))
				{
					if (this._Sub_System.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSUB_SYSChanging(value);
					this.SendPropertyChanging();
					this._SUB_SYS = value;
					this.SendPropertyChanged("SUB_SYS");
					this.OnSUB_SYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_TYPE", DbType="VarChar(3)")]
		public string LINE_TYPE
		{
			get
			{
				return this._LINE_TYPE;
			}
			set
			{
				if ((this._LINE_TYPE != value))
				{
					this.OnLINE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._LINE_TYPE = value;
					this.SendPropertyChanged("LINE_TYPE");
					this.OnLINE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTN_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ACTN_DATE
		{
			get
			{
				return this._ACTN_DATE;
			}
			set
			{
				if ((this._ACTN_DATE != value))
				{
					this.OnACTN_DATEChanging(value);
					this.SendPropertyChanging();
					this._ACTN_DATE = value;
					this.SendPropertyChanged("ACTN_DATE");
					this.OnACTN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFID", DbType="BigInt")]
		public System.Nullable<long> RFID
		{
			get
			{
				return this._RFID;
			}
			set
			{
				if ((this._RFID != value))
				{
					this.OnRFIDChanging(value);
					this.SendPropertyChanging();
					this._RFID = value;
					this.SendPropertyChanged("RFID");
					this.OnRFIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHON_NUMB", DbType="VarChar(11)")]
		public string PHON_NUMB
		{
			get
			{
				return this._PHON_NUMB;
			}
			set
			{
				if ((this._PHON_NUMB != value))
				{
					this.OnPHON_NUMBChanging(value);
					this.SendPropertyChanging();
					this._PHON_NUMB = value;
					this.SendPropertyChanged("PHON_NUMB");
					this.OnPHON_NUMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGB_TEXT", DbType="NVarChar(MAX)")]
		public string MSGB_TEXT
		{
			get
			{
				return this._MSGB_TEXT;
			}
			set
			{
				if ((this._MSGB_TEXT != value))
				{
					this.OnMSGB_TEXTChanging(value);
					this.SendPropertyChanging();
					this._MSGB_TEXT = value;
					this.SendPropertyChanged("MSGB_TEXT");
					this.OnMSGB_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSGB_TYPE", DbType="VarChar(3)")]
		public string MSGB_TYPE
		{
			get
			{
				return this._MSGB_TYPE;
			}
			set
			{
				if ((this._MSGB_TYPE != value))
				{
					this.OnMSGB_TYPEChanging(value);
					this.SendPropertyChanging();
					this._MSGB_TYPE = value;
					this.SendPropertyChanged("MSGB_TYPE");
					this.OnMSGB_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT", DbType="VarChar(3)")]
		public string STAT
		{
			get
			{
				return this._STAT;
			}
			set
			{
				if ((this._STAT != value))
				{
					this.OnSTATChanging(value);
					this.SendPropertyChanging();
					this._STAT = value;
					this.SendPropertyChanged("STAT");
					this.OnSTATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESG_ID", DbType="VarChar(50)")]
		public string MESG_ID
		{
			get
			{
				return this._MESG_ID;
			}
			set
			{
				if ((this._MESG_ID != value))
				{
					this.OnMESG_IDChanging(value);
					this.SendPropertyChanging();
					this._MESG_ID = value;
					this.SendPropertyChanged("MESG_ID");
					this.OnMESG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EROR_CODE", DbType="VarChar(10)")]
		public string EROR_CODE
		{
			get
			{
				return this._EROR_CODE;
			}
			set
			{
				if ((this._EROR_CODE != value))
				{
					this.OnEROR_CODEChanging(value);
					this.SendPropertyChanging();
					this._EROR_CODE = value;
					this.SendPropertyChanged("EROR_CODE");
					this.OnEROR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EROR_MESG", DbType="NVarChar(500)")]
		public string EROR_MESG
		{
			get
			{
				return this._EROR_MESG;
			}
			set
			{
				if ((this._EROR_MESG != value))
				{
					this.OnEROR_MESGChanging(value);
					this.SendPropertyChanging();
					this._EROR_MESG = value;
					this.SendPropertyChanged("EROR_MESG");
					this.OnEROR_MESGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRVR_SEND_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SRVR_SEND_DATE
		{
			get
			{
				return this._SRVR_SEND_DATE;
			}
			set
			{
				if ((this._SRVR_SEND_DATE != value))
				{
					this.OnSRVR_SEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._SRVR_SEND_DATE = value;
					this.SendPropertyChanged("SRVR_SEND_DATE");
					this.OnSRVR_SEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESG_LENT", DbType="Int")]
		public System.Nullable<int> MESG_LENT
		{
			get
			{
				return this._MESG_LENT;
			}
			set
			{
				if ((this._MESG_LENT != value))
				{
					this.OnMESG_LENTChanging(value);
					this.SendPropertyChanging();
					this._MESG_LENT = value;
					this.SendPropertyChanged("MESG_LENT");
					this.OnMESG_LENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRET_BY", DbType="VarChar(250)")]
		public string CRET_BY
		{
			get
			{
				return this._CRET_BY;
			}
			set
			{
				if ((this._CRET_BY != value))
				{
					this.OnCRET_BYChanging(value);
					this.SendPropertyChanging();
					this._CRET_BY = value;
					this.SendPropertyChanged("CRET_BY");
					this.OnCRET_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRET_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRET_DATE
		{
			get
			{
				return this._CRET_DATE;
			}
			set
			{
				if ((this._CRET_DATE != value))
				{
					this.OnCRET_DATEChanging(value);
					this.SendPropertyChanging();
					this._CRET_DATE = value;
					this.SendPropertyChanged("CRET_DATE");
					this.OnCRET_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDFY_BY", DbType="VarChar(250)")]
		public string MDFY_BY
		{
			get
			{
				return this._MDFY_BY;
			}
			set
			{
				if ((this._MDFY_BY != value))
				{
					this.OnMDFY_BYChanging(value);
					this.SendPropertyChanging();
					this._MDFY_BY = value;
					this.SendPropertyChanged("MDFY_BY");
					this.OnMDFY_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDFY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MDFY_DATE
		{
			get
			{
				return this._MDFY_DATE;
			}
			set
			{
				if ((this._MDFY_DATE != value))
				{
					this.OnMDFY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MDFY_DATE = value;
					this.SendPropertyChanged("MDFY_DATE");
					this.OnMDFY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sub_System_Sms_Message_Box", Storage="_Sub_System", ThisKey="SUB_SYS", OtherKey="SUB_SYS", IsForeignKey=true)]
		public Sub_System Sub_System
		{
			get
			{
				return this._Sub_System.Entity;
			}
			set
			{
				Sub_System previousValue = this._Sub_System.Entity;
				if (((previousValue != value) 
							|| (this._Sub_System.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sub_System.Entity = null;
						previousValue.Sms_Message_Boxes.Remove(this);
					}
					this._Sub_System.Entity = value;
					if ((value != null))
					{
						value.Sms_Message_Boxes.Add(this);
						this._SUB_SYS = value.SUB_SYS;
					}
					else
					{
						this._SUB_SYS = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sub_System");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Msgb.Message_Broad_Settings")]
	public partial class Message_Broad_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MBID;
		
		private string _TYPE;
		
		private string _BGWK_STAT;
		
		private System.Nullable<int> _BGWK_INTR;
		
		private string _CUST_BGWK_STAT;
		
		private System.Nullable<int> _CUST_BGWK_INTR;
		
		private string _USER_NAME;
		
		private string _PASS_WORD;
		
		private string _LINE_NUMB;
		
		private string _LINE_TYPE;
		
		private string _DFLT_STAT;
		
		private System.Nullable<long> _LAST_ROW_FTCH;
		
		private System.Nullable<int> _FTCH_ROW;
		
		private string _CRET_BY;
		
		private System.Nullable<System.DateTime> _CRET_DATE;
		
		private string _MDFY_BY;
		
		private System.Nullable<System.DateTime> _MDFY_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMBIDChanging(long value);
    partial void OnMBIDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnBGWK_STATChanging(string value);
    partial void OnBGWK_STATChanged();
    partial void OnBGWK_INTRChanging(System.Nullable<int> value);
    partial void OnBGWK_INTRChanged();
    partial void OnCUST_BGWK_STATChanging(string value);
    partial void OnCUST_BGWK_STATChanged();
    partial void OnCUST_BGWK_INTRChanging(System.Nullable<int> value);
    partial void OnCUST_BGWK_INTRChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnPASS_WORDChanging(string value);
    partial void OnPASS_WORDChanged();
    partial void OnLINE_NUMBChanging(string value);
    partial void OnLINE_NUMBChanged();
    partial void OnLINE_TYPEChanging(string value);
    partial void OnLINE_TYPEChanged();
    partial void OnDFLT_STATChanging(string value);
    partial void OnDFLT_STATChanged();
    partial void OnLAST_ROW_FTCHChanging(System.Nullable<long> value);
    partial void OnLAST_ROW_FTCHChanged();
    partial void OnFTCH_ROWChanging(System.Nullable<int> value);
    partial void OnFTCH_ROWChanged();
    partial void OnCRET_BYChanging(string value);
    partial void OnCRET_BYChanged();
    partial void OnCRET_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCRET_DATEChanged();
    partial void OnMDFY_BYChanging(string value);
    partial void OnMDFY_BYChanged();
    partial void OnMDFY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMDFY_DATEChanged();
    #endregion
		
		public Message_Broad_Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MBID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MBID
		{
			get
			{
				return this._MBID;
			}
			set
			{
				if ((this._MBID != value))
				{
					this.OnMBIDChanging(value);
					this.SendPropertyChanging();
					this._MBID = value;
					this.SendPropertyChanged("MBID");
					this.OnMBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGWK_STAT", DbType="VarChar(3)")]
		public string BGWK_STAT
		{
			get
			{
				return this._BGWK_STAT;
			}
			set
			{
				if ((this._BGWK_STAT != value))
				{
					this.OnBGWK_STATChanging(value);
					this.SendPropertyChanging();
					this._BGWK_STAT = value;
					this.SendPropertyChanged("BGWK_STAT");
					this.OnBGWK_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGWK_INTR", DbType="Int")]
		public System.Nullable<int> BGWK_INTR
		{
			get
			{
				return this._BGWK_INTR;
			}
			set
			{
				if ((this._BGWK_INTR != value))
				{
					this.OnBGWK_INTRChanging(value);
					this.SendPropertyChanging();
					this._BGWK_INTR = value;
					this.SendPropertyChanged("BGWK_INTR");
					this.OnBGWK_INTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_BGWK_STAT", DbType="VarChar(3)")]
		public string CUST_BGWK_STAT
		{
			get
			{
				return this._CUST_BGWK_STAT;
			}
			set
			{
				if ((this._CUST_BGWK_STAT != value))
				{
					this.OnCUST_BGWK_STATChanging(value);
					this.SendPropertyChanging();
					this._CUST_BGWK_STAT = value;
					this.SendPropertyChanged("CUST_BGWK_STAT");
					this.OnCUST_BGWK_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_BGWK_INTR", DbType="Int")]
		public System.Nullable<int> CUST_BGWK_INTR
		{
			get
			{
				return this._CUST_BGWK_INTR;
			}
			set
			{
				if ((this._CUST_BGWK_INTR != value))
				{
					this.OnCUST_BGWK_INTRChanging(value);
					this.SendPropertyChanging();
					this._CUST_BGWK_INTR = value;
					this.SendPropertyChanged("CUST_BGWK_INTR");
					this.OnCUST_BGWK_INTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(250)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS_WORD", DbType="VarChar(250)")]
		public string PASS_WORD
		{
			get
			{
				return this._PASS_WORD;
			}
			set
			{
				if ((this._PASS_WORD != value))
				{
					this.OnPASS_WORDChanging(value);
					this.SendPropertyChanging();
					this._PASS_WORD = value;
					this.SendPropertyChanged("PASS_WORD");
					this.OnPASS_WORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_NUMB", DbType="VarChar(30)")]
		public string LINE_NUMB
		{
			get
			{
				return this._LINE_NUMB;
			}
			set
			{
				if ((this._LINE_NUMB != value))
				{
					this.OnLINE_NUMBChanging(value);
					this.SendPropertyChanging();
					this._LINE_NUMB = value;
					this.SendPropertyChanged("LINE_NUMB");
					this.OnLINE_NUMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_TYPE", DbType="VarChar(3)")]
		public string LINE_TYPE
		{
			get
			{
				return this._LINE_TYPE;
			}
			set
			{
				if ((this._LINE_TYPE != value))
				{
					this.OnLINE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._LINE_TYPE = value;
					this.SendPropertyChanged("LINE_TYPE");
					this.OnLINE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DFLT_STAT", DbType="VarChar(3)")]
		public string DFLT_STAT
		{
			get
			{
				return this._DFLT_STAT;
			}
			set
			{
				if ((this._DFLT_STAT != value))
				{
					this.OnDFLT_STATChanging(value);
					this.SendPropertyChanging();
					this._DFLT_STAT = value;
					this.SendPropertyChanged("DFLT_STAT");
					this.OnDFLT_STATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_ROW_FTCH", DbType="BigInt")]
		public System.Nullable<long> LAST_ROW_FTCH
		{
			get
			{
				return this._LAST_ROW_FTCH;
			}
			set
			{
				if ((this._LAST_ROW_FTCH != value))
				{
					this.OnLAST_ROW_FTCHChanging(value);
					this.SendPropertyChanging();
					this._LAST_ROW_FTCH = value;
					this.SendPropertyChanged("LAST_ROW_FTCH");
					this.OnLAST_ROW_FTCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTCH_ROW", DbType="Int")]
		public System.Nullable<int> FTCH_ROW
		{
			get
			{
				return this._FTCH_ROW;
			}
			set
			{
				if ((this._FTCH_ROW != value))
				{
					this.OnFTCH_ROWChanging(value);
					this.SendPropertyChanging();
					this._FTCH_ROW = value;
					this.SendPropertyChanged("FTCH_ROW");
					this.OnFTCH_ROWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRET_BY", DbType="VarChar(250)")]
		public string CRET_BY
		{
			get
			{
				return this._CRET_BY;
			}
			set
			{
				if ((this._CRET_BY != value))
				{
					this.OnCRET_BYChanging(value);
					this.SendPropertyChanging();
					this._CRET_BY = value;
					this.SendPropertyChanged("CRET_BY");
					this.OnCRET_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRET_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRET_DATE
		{
			get
			{
				return this._CRET_DATE;
			}
			set
			{
				if ((this._CRET_DATE != value))
				{
					this.OnCRET_DATEChanging(value);
					this.SendPropertyChanging();
					this._CRET_DATE = value;
					this.SendPropertyChanged("CRET_DATE");
					this.OnCRET_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDFY_BY", DbType="VarChar(250)")]
		public string MDFY_BY
		{
			get
			{
				return this._MDFY_BY;
			}
			set
			{
				if ((this._MDFY_BY != value))
				{
					this.OnMDFY_BYChanging(value);
					this.SendPropertyChanging();
					this._MDFY_BY = value;
					this.SendPropertyChanged("MDFY_BY");
					this.OnMDFY_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDFY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MDFY_DATE
		{
			get
			{
				return this._MDFY_DATE;
			}
			set
			{
				if ((this._MDFY_DATE != value))
				{
					this.OnMDFY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MDFY_DATE = value;
					this.SendPropertyChanged("MDFY_DATE");
					this.OnMDFY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PrepareSendCustSmsResult
	{
		
		private int _Column1;
		
		public PrepareSendCustSmsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
