//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CATEGORY
    {
        public ADM_CATEGORY()
        {
            this.BIL_TARIFF = new HashSet<BIL_TARIFF>();
        }
    
        public short CODE { get; set; }
        public string CONS_CODE { get; set; }
        public string CTGY_DESC { get; set; }
        public string TRAN_STAT { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string CRET_BY { get; set; }
    
        public virtual ICollection<BIL_TARIFF> BIL_TARIFF { get; set; }
    }
}
