//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_BRANCH
    {
        public BANK_BRANCH()
        {
            this.BANK_ACCOUNT = new HashSet<BANK_ACCOUNT>();
        }
    
        public short BANK_CODE { get; set; }
        public int CODE { get; set; }
        public string NAME { get; set; }
        public string STAT { get; set; }
        public string ADDR { get; set; }
        public string TRAN_STAT { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string CRET_BY { get; set; }
        public string TEL { get; set; }
        public Nullable<int> HEAD_CODE { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual ICollection<BANK_ACCOUNT> BANK_ACCOUNT { get; set; }
    }
}
