//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        public BANK()
        {
            this.BANK_BRANCH = new HashSet<BANK_BRANCH>();
        }
    
        public short CODE { get; set; }
        public string BANK_DESC { get; set; }
        public string TRAN_STAT { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string CRET_BY { get; set; }
        public string TITL { get; set; }
    
        public virtual ICollection<BANK_BRANCH> BANK_BRANCH { get; set; }
    }
}
