//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_ACCOUNT
    {
        public BANK_ACCOUNT()
        {
            this.ADM_REGION_EXPENSE_ACOUNT = new HashSet<ADM_REGION_EXPENSE_ACOUNT>();
            this.REQUEST_ROW = new HashSet<REQUEST_ROW>();
        }
    
        public short BNKB_BANK_CODE { get; set; }
        public int BNKB_CODE { get; set; }
        public string ACNT_NUMB { get; set; }
        public string ACNT_NAME { get; set; }
        public string ACNT_TYPE { get; set; }
        public string OWNR_TYPE { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public string SHBA_ACNT { get; set; }
    
        public virtual ICollection<ADM_REGION_EXPENSE_ACOUNT> ADM_REGION_EXPENSE_ACOUNT { get; set; }
        public virtual BANK_BRANCH BANK_BRANCH { get; set; }
        public virtual ICollection<REQUEST_ROW> REQUEST_ROW { get; set; }
    }
}
