//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIL_RCPT_ROW_ANNOUNCEMENT
    {
        public short RCPA_RCPN_RCPT_SEQ { get; set; }
        public System.DateTime RCPA_ANNC_DATE { get; set; }
        public short RCPA_BNKB_BANK_CODE { get; set; }
        public int RCPA_BNKB_CODE { get; set; }
        public string BILL_REGN_CODE { get; set; }
        public int BILL_SERV_FILE_NO { get; set; }
        public short BILL_BILL_NO { get; set; }
        public short RWNO { get; set; }
        public long RCPT_AMNT { get; set; }
        public string RCPT_METD { get; set; }
        public string ACTN_STAT { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string RCPT_STAT { get; set; }
        public Nullable<long> DISC_AMNT_DNRM { get; set; }
        public Nullable<short> INSM_SER_DNRM { get; set; }
        public string BRNC_CODE { get; set; }
        public string RFNC_CODE { get; set; }
    
        public virtual BILL BILL { get; set; }
    }
}
