//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIL_ACCOUNT_DETAIL
    {
        public int ACNT_SERV_FILE_NO { get; set; }
        public short ACNT_RWNO { get; set; }
        public string REMN_TYPE { get; set; }
        public long AMNT { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
    
        public virtual BIL_ACCOUNT BIL_ACCOUNT { get; set; }
    }
}
