//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIL_BILL_AMOUNT
    {
        public string FINF_CYCL_YEAR { get; set; }
        public string FINF_PRVN_CODE { get; set; }
        public string FINF_LETT_NO { get; set; }
        public int BILL_SERV_FILE_NO { get; set; }
        public string BILL_REGN_CODE { get; set; }
        public short BILL_BILL_NO { get; set; }
        public string AMNT_TYPE { get; set; }
        public string SESN_CODE { get; set; }
        public long AMNT { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual BIL_FIRST_INFORMATION BIL_FIRST_INFORMATION { get; set; }
    }
}
