//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIL_CONSUMPTION_DETAIL
    {
        public string FINF_PRVN_CODE { get; set; }
        public string FINF_CYCL_YEAR { get; set; }
        public string FINF_LETT_NO { get; set; }
        public string CONS_BILL_REGN_CODE { get; set; }
        public int CONS_BILL_SERV_FILE_NO { get; set; }
        public short CONS_BILL_BILL_NO { get; set; }
        public string CONS_BMTR_METR_TARF_TYPE { get; set; }
        public string CONS_BMTR_DAY_TYPE { get; set; }
        public string SESN_TYPE { get; set; }
        public string EXCD_TYPE { get; set; }
        public decimal CONS { get; set; }
        public short NUMB_OF_DAY { get; set; }
        public long POWR_AMNT { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public Nullable<decimal> CONS_AVRG { get; set; }
    
        public virtual BIL_CONSUMPTION BIL_CONSUMPTION { get; set; }
        public virtual BIL_FIRST_INFORMATION BIL_FIRST_INFORMATION { get; set; }
    }
}
