//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIL_ACCOUNT
    {
        public BIL_ACCOUNT()
        {
            this.BIL_ACCOUNT_DETAIL = new HashSet<BIL_ACCOUNT_DETAIL>();
        }
    
        public int SERV_FILE_NO { get; set; }
        public short RWNO { get; set; }
        public string REGN_CODE { get; set; }
        public string ACTN_CODE { get; set; }
        public long AMNT { get; set; }
        public System.DateTime AMNT_DATE { get; set; }
        public string DEBT_STAT { get; set; }
        public long REMN_DNRM { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string LETT_NO_DNRM { get; set; }
        public Nullable<System.DateTime> LETT_DATE_DNRM { get; set; }
        public Nullable<short> BILL_NO_DNRM { get; set; }
    
        public virtual ICollection<BIL_ACCOUNT_DETAIL> BIL_ACCOUNT_DETAIL { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
