//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public BILL()
        {
            this.BIL_CONSUMPTION = new HashSet<BIL_CONSUMPTION>();
            this.BILL1 = new HashSet<BILL>();
            this.BIL_BILL_DEBIT = new HashSet<BIL_BILL_DEBIT>();
            this.BIL_BILL_AMOUNT = new HashSet<BIL_BILL_AMOUNT>();
            this.BIL_RCPT_ROW_ANNOUNCEMENT = new HashSet<BIL_RCPT_ROW_ANNOUNCEMENT>();
        }
    
        public string REGN_CODE { get; set; }
        public int SERV_FILE_NO { get; set; }
        public short BILL_NO { get; set; }
        public short MSRT_STRF_RWNO { get; set; }
        public int MSRT_METR_MTID { get; set; }
        public short PBLC_RECT_CODE { get; set; }
        public short PBLC_RWNO { get; set; }
        public string PRCD_CODE { get; set; }
        public string BILL_VLID { get; set; }
        public Nullable<int> PACT_SEQ { get; set; }
        public string BILL_TYPE { get; set; }
        public string BILL_STAT { get; set; }
        public string YEAR { get; set; }
        public string CYCL { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string BILL_REGN_CODE { get; set; }
        public Nullable<int> BILL_SERV_FILE_NO { get; set; }
        public Nullable<short> BILL_BILL_NO { get; set; }
        public Nullable<int> RQRO_RQST_RQID { get; set; }
        public Nullable<short> RQRO_RWNO { get; set; }
        public Nullable<System.DateTime> PRVS_DATE { get; set; }
        public Nullable<System.DateTime> CRNT_DATE { get; set; }
        public Nullable<short> NUMB_OF_DAY_DNRM { get; set; }
        public Nullable<short> COLD_DAY_DNRM { get; set; }
        public Nullable<short> WARM_DAY_DNRM { get; set; }
        public Nullable<short> HOT_DAY_DNRM { get; set; }
        public Nullable<short> PEAK_DAY_DNRM { get; set; }
        public Nullable<System.DateTime> ISSU_DATE { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public Nullable<System.DateTime> CNCL_DATE { get; set; }
        public string HILO_TYPE { get; set; }
        public string MIN_STAT { get; set; }
        public Nullable<int> READ_DMND { get; set; }
        public Nullable<decimal> MAXI_READ { get; set; }
        public Nullable<decimal> POWR_COEF { get; set; }
        public Nullable<decimal> LOSS_COEF { get; set; }
        public Nullable<decimal> CALC_DMND_DNRM { get; set; }
        public Nullable<decimal> LGHT_CONS_PERC { get; set; }
        public Nullable<decimal> INVL_CONS_PERC { get; set; }
        public Nullable<long> CYCL_AMNT_DNRM { get; set; }
        public Nullable<long> TOTL_DEBT_DNRM { get; set; }
        public Nullable<short> REMN_RIAL_DNRM { get; set; }
        public Nullable<long> TOTL_AMNT_DNRM { get; set; }
        public Nullable<long> RCPT_AMNT_DNRM { get; set; }
        public string RCPT_METD { get; set; }
        public Nullable<System.DateTime> RCPT_DATE { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public Nullable<System.DateTime> READ_CRNT_DATE { get; set; }
        public string READ_FABR { get; set; }
        public string READ_METD { get; set; }
        public string ACT1_STAT { get; set; }
        public Nullable<int> BILL_SEQN { get; set; }
        public Nullable<long> DISC_91 { get; set; }
    
        public virtual ICollection<BIL_CONSUMPTION> BIL_CONSUMPTION { get; set; }
        public virtual ICollection<BILL> BILL1 { get; set; }
        public virtual BILL BILL2 { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REQUEST_ROW REQUEST_ROW { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual BIL_PREVENT_CODE BIL_PREVENT_CODE { get; set; }
        public virtual ICollection<BIL_BILL_DEBIT> BIL_BILL_DEBIT { get; set; }
        public virtual ICollection<BIL_BILL_AMOUNT> BIL_BILL_AMOUNT { get; set; }
        public virtual SAS_PUBLIC SAS_PUBLIC { get; set; }
        public virtual ICollection<BIL_RCPT_ROW_ANNOUNCEMENT> BIL_RCPT_ROW_ANNOUNCEMENT { get; set; }
    }
}
