//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CG_REF_CODES
    {
        public string RV_DOMAIN { get; set; }
        public string RV_LOW_VALUE { get; set; }
        public string RV_HIGH_VALUE { get; set; }
        public string RV_ABBREVIATION { get; set; }
        public string RV_MEANING { get; set; }
    }
}
