//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCLE
    {
        public CYCLE()
        {
            this.BIL_FIRST_INFORMATION = new HashSet<BIL_FIRST_INFORMATION>();
            this.REGULATION = new HashSet<REGULATION>();
            this.REQUEST = new HashSet<REQUEST>();
        }
    
        public string YEAR { get; set; }
        public string TRAN_STAT { get; set; }
    
        public virtual ICollection<BIL_FIRST_INFORMATION> BIL_FIRST_INFORMATION { get; set; }
        public virtual ICollection<REGULATION> REGULATION { get; set; }
        public virtual ICollection<REQUEST> REQUEST { get; set; }
    }
}
