//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSE_TYPE
    {
        public EXPENSE_TYPE()
        {
            this.EXPENSE = new HashSet<EXPENSE>();
            this.ADM_REGION_EXPENSE_ACOUNT = new HashSet<ADM_REGION_EXPENSE_ACOUNT>();
        }
    
        public int CODE { get; set; }
        public string EXTP_DESC { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string MATR_STAT { get; set; }
        public string RQRQ_REGL_CYCL_YEAR { get; set; }
        public Nullable<short> RQRQ_REGL_CODE { get; set; }
        public Nullable<short> RQRQ_RQTT_CODE { get; set; }
        public Nullable<short> RQRQ_RQTP_CODE { get; set; }
        public Nullable<short> EPIT_CODE { get; set; }
        public string RFRN { get; set; }
        public string EXTP_TYPE { get; set; }
        public Nullable<int> REF_CODE { get; set; }
        public string BRNC_TYPE { get; set; }
    
        public virtual ICollection<EXPENSE> EXPENSE { get; set; }
        public virtual SAS_EXPENSE_ITEM SAS_EXPENSE_ITEM { get; set; }
        public virtual SAS_REQUEST_REQUESTER SAS_REQUEST_REQUESTER { get; set; }
        public virtual ICollection<ADM_REGION_EXPENSE_ACOUNT> ADM_REGION_EXPENSE_ACOUNT { get; set; }
    }
}
