//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class METER_SPEC
    {
        public int SERV_FILE_NO { get; set; }
        public short RECT_CODE { get; set; }
        public short RWNO { get; set; }
        public string REGN_CODE { get; set; }
        public int RQRO_RQST_RQID { get; set; }
        public short RQRO_RWNO { get; set; }
        public string REC_STAT { get; set; }
        public System.DateTime ACTN_DATE { get; set; }
        public string CYCL_YEAR_DNRM { get; set; }
        public string REGN_CODE_DNRM { get; set; }
        public short RQTP_CODE_DNRM { get; set; }
        public int RWNO_DNRM { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public Nullable<short> RESN_RQTP_CODE { get; set; }
        public Nullable<short> RESN_RWNO { get; set; }
        public Nullable<short> REF_SEQ { get; set; }
        public string ACTN_TYPE { get; set; }
        public string ACTN_RSLT { get; set; }
        public string VIST_MABY_RSLT { get; set; }
        public string RSLT_OTHR_RESN { get; set; }
        public string METR_TYPE { get; set; }
        public string ACTV_FABR_NO { get; set; }
        public string RACT_FABR_NO { get; set; }
        public string PLUM_NO1 { get; set; }
        public string PLUM_NO2 { get; set; }
        public string CABL_SIZE { get; set; }
        public Nullable<int> CABL_LENG { get; set; }
        public string BRNC_TYPE { get; set; }
        public Nullable<System.DateTime> DECR_END_DATE { get; set; }
        public string CITY_LIMT { get; set; }
        public Nullable<int> MNTC_COST { get; set; }
        public string SESN_ACTV { get; set; }
        public string SESN_STRT_MONT { get; set; }
        public string SESN_END_MONT { get; set; }
        public Nullable<int> CT_FRST_AMPR { get; set; }
        public Nullable<int> CT_SCND_AMPR { get; set; }
        public Nullable<int> PT_FRST_VOLT { get; set; }
        public Nullable<int> PT_SCND_VOLT { get; set; }
        public string LIMT_KEY { get; set; }
        public Nullable<int> AMPR_LIMT_KEY { get; set; }
        public string CPTR { get; set; }
        public Nullable<int> CPTR_CPTY { get; set; }
        public Nullable<int> ADD_MAXI_DIGT { get; set; }
        public Nullable<int> ADD_MAXI_NO { get; set; }
        public string ADD_MAXI_CODE { get; set; }
        public string WTCH_FABR_NO { get; set; }
        public string POWR_CHNG_TYPE { get; set; }
        public Nullable<System.DateTime> EQUP_CHNG_DATE { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public Nullable<short> FLEZ_NUMB { get; set; }
        public Nullable<short> CABL_GIR { get; set; }
        public Nullable<short> CONT_NUMB { get; set; }
        public Nullable<short> PRTC_PIPE { get; set; }
        public Nullable<short> CABL_SHOO { get; set; }
        public Nullable<short> PUSE_PHAS { get; set; }
        public Nullable<short> TERM_CHIN { get; set; }
        public string TYPE_CONT { get; set; }
        public string SYST_ADDR { get; set; }
        public string METR_ADDR { get; set; }
        public Nullable<short> BMTT_RWNO { get; set; }
        public Nullable<short> WELL_DEPT { get; set; }
        public string LETT_NO { get; set; }
        public Nullable<int> DEBI { get; set; }
        public string FIDR_CODE { get; set; }
        public string HOUR_ACT2 { get; set; }
        public string CNTT_NUMB { get; set; }
        public string METR_MODL { get; set; }
        public string WARN_SRIL { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual REQUEST_ROW REQUEST_ROW { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual SAS_REC_TYPE SAS_REC_TYPE { get; set; }
    }
}
