//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.BASE_METER_SPEC = new HashSet<BASE_METER_SPEC>();
            this.METER_SPEC = new HashSet<METER_SPEC>();
            this.REGION1 = new HashSet<REGION>();
            this.REQUEST_ROW = new HashSet<REQUEST_ROW>();
            this.REQUEST = new HashSet<REQUEST>();
            this.REQUEST1 = new HashSet<REQUEST>();
            this.SERVICE = new HashSet<SERVICE>();
            this.BILL = new HashSet<BILL>();
            this.SAS_PUBLIC = new HashSet<SAS_PUBLIC>();
            this.SERVICE_TARIFF = new HashSet<SERVICE_TARIFF>();
            this.BIL_ACCOUNT = new HashSet<BIL_ACCOUNT>();
            this.ADM_REGION_EXPENSE_ACOUNT = new HashSet<ADM_REGION_EXPENSE_ACOUNT>();
        }
    
        public string CODE { get; set; }
        public string DSCO_PRVN_CODE { get; set; }
        public string DSCO_CODE { get; set; }
        public string NAME { get; set; }
        public string CLMT_CODE { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string REGN_TEL1 { get; set; }
        public string REGN_TEL2 { get; set; }
        public string EMGY_TEL1 { get; set; }
        public string EMGY_TEL2 { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public string REGN_CODE { get; set; }
        public string ADDR { get; set; }
        public string MNGR_NAME { get; set; }
        public string BTCH { get; set; }
    
        public virtual ICollection<BASE_METER_SPEC> BASE_METER_SPEC { get; set; }
        public virtual ICollection<METER_SPEC> METER_SPEC { get; set; }
        public virtual ICollection<REGION> REGION1 { get; set; }
        public virtual REGION REGION2 { get; set; }
        public virtual ICollection<REQUEST_ROW> REQUEST_ROW { get; set; }
        public virtual ICollection<REQUEST> REQUEST { get; set; }
        public virtual ICollection<REQUEST> REQUEST1 { get; set; }
        public virtual ICollection<SERVICE> SERVICE { get; set; }
        public virtual ICollection<BILL> BILL { get; set; }
        public virtual ICollection<SAS_PUBLIC> SAS_PUBLIC { get; set; }
        public virtual ICollection<SERVICE_TARIFF> SERVICE_TARIFF { get; set; }
        public virtual ICollection<BIL_ACCOUNT> BIL_ACCOUNT { get; set; }
        public virtual ICollection<ADM_REGION_EXPENSE_ACOUNT> ADM_REGION_EXPENSE_ACOUNT { get; set; }
    }
}
