//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_PUBLIC
    {
        public SAS_PUBLIC()
        {
            this.BILL = new HashSet<BILL>();
        }
    
        public short RECT_CODE { get; set; }
        public int SERV_FILE_NO { get; set; }
        public short RWNO { get; set; }
        public int METR_MTID { get; set; }
        public int RQRO_RQST_RQID { get; set; }
        public short RQRO_RWNO { get; set; }
        public string REGN_CODE { get; set; }
        public string WTYP_CTGY_CONS_CODE { get; set; }
        public Nullable<short> WTYP_CTGY_CODE { get; set; }
        public Nullable<short> WTYP_CODE { get; set; }
        public string BLOK_WDAY_REGN_CODE { get; set; }
        public string BLOK_WDAY_CODE { get; set; }
        public string BLOK_CODE { get; set; }
        public Nullable<short> RESN_RQTP_CODE { get; set; }
        public Nullable<short> RESN_RWNO { get; set; }
        public string SUNT_BUNT_DEPT_ORGN_CODE { get; set; }
        public string SUNT_BUNT_DEPT_CODE { get; set; }
        public string SUNT_BUNT_CODE { get; set; }
        public string SUNT_CODE { get; set; }
        public string REC_STAT { get; set; }
        public System.DateTime ACTN_DATE { get; set; }
        public int RWNO_DNRM { get; set; }
        public short BMSP_RWNO_DNRM { get; set; }
        public short MSPC_RWNO_DNRM { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public Nullable<short> REF_SEQ { get; set; }
        public string NAME { get; set; }
        public string CLMT_TYPE { get; set; }
        public Nullable<short> FMLY_NUMB { get; set; }
        public string SERV_TYPE { get; set; }
        public string SERV_NO { get; set; }
        public string POST_ADDR { get; set; }
        public string SERV_ADDR { get; set; }
        public string ZIP_CODE { get; set; }
        public string EMIL_ADDR { get; set; }
        public string CUST_TEL { get; set; }
        public string CELL_PHON { get; set; }
        public string HSPL_CODE { get; set; }
        public string BILL_LCTN { get; set; }
        public string ZONE_CODE { get; set; }
        public string OWNR_TYPE { get; set; }
        public string ID_CODE { get; set; }
        public string SEQ { get; set; }
        public string OLD_IDNT { get; set; }
        public string RISK_CODE { get; set; }
        public Nullable<decimal> RISK_COEF { get; set; }
        public Nullable<System.DateTime> TEMP_END_DATE { get; set; }
        public string INST_LOC { get; set; }
        public string CHLC_COND { get; set; }
        public string CABL_SIZE { get; set; }
        public Nullable<int> CABL_LENG { get; set; }
        public string ACTN_RSLT { get; set; }
        public string VIST_MABY_RSLT { get; set; }
        public string RSLT_OTHR_RESN { get; set; }
        public string CONT_STAT { get; set; }
        public string FATH_NAME { get; set; }
        public string SHEN_NUMB { get; set; }
        public string ISSU_LOCT { get; set; }
        public string ISCP_ISCA_ISCG_CODE { get; set; }
        public string ISCP_ISCA_ISCG_CONS_CODE { get; set; }
        public string ISCP_ISCA_CODE { get; set; }
        public string ISCP_CODE { get; set; }
        public string SHAD_CODE { get; set; }
        public Nullable<int> CORD_X { get; set; }
        public Nullable<int> CORD_Y { get; set; }
        public string PRSN_TYPE { get; set; }
        public string HSPL_TYPE { get; set; }
        public Nullable<short> SCTN_NUMB { get; set; }
        public Nullable<short> FLOR_NUMB { get; set; }
        public Nullable<int> BULD_AREA { get; set; }
    
        public virtual ICollection<BILL> BILL { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REQUEST_ROW REQUEST_ROW { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        public virtual SAS_REC_TYPE SAS_REC_TYPE { get; set; }
    }
}
