//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_REC_TYPE
    {
        public SAS_REC_TYPE()
        {
            this.BASE_METER_SPEC = new HashSet<BASE_METER_SPEC>();
            this.METER_SPEC = new HashSet<METER_SPEC>();
            this.SAS_PUBLIC = new HashSet<SAS_PUBLIC>();
        }
    
        public short CODE { get; set; }
        public string RECT_DESC { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
    
        public virtual ICollection<BASE_METER_SPEC> BASE_METER_SPEC { get; set; }
        public virtual ICollection<METER_SPEC> METER_SPEC { get; set; }
        public virtual ICollection<SAS_PUBLIC> SAS_PUBLIC { get; set; }
    }
}
