//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_REQUEST_DOCUMENT
    {
        public int RDID { get; set; }
        public short DCMT_RWNO { get; set; }
        public string RQRQ_REGL_CYCL_YEAR { get; set; }
        public short RQRQ_REGL_CODE { get; set; }
        public short RQRQ_RQTP_CODE { get; set; }
        public short RQRQ_RQTT_CODE { get; set; }
        public string NEED_TYPE { get; set; }
        public string ORIN_TYPE { get; set; }
        public string FRST_NEED { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string FRST_CONS { get; set; }
        public string SCND_CONS { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public string PERM_TYPE { get; set; }
    
        public virtual SAS_DOCUMENT_SPEC SAS_DOCUMENT_SPEC { get; set; }
        public virtual SAS_REQUEST_REQUESTER SAS_REQUEST_REQUESTER { get; set; }
    }
}
