//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_BRANCH_SYSTEM
    {
        public int RQRO_RQST_RQID { get; set; }
        public short RQRO_RWNO { get; set; }
        public short RWNO { get; set; }
        public string REC_STAT { get; set; }
        public string PRIC_TYPE { get; set; }
        public long PRIC { get; set; }
        public string TRAN_STAT { get; set; }
        public string ARCH_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public Nullable<decimal> PRCNT { get; set; }
        public Nullable<long> CALC_PRIC { get; set; }
        public Nullable<long> PRIC_INST { get; set; }
        public Nullable<long> RELC_AMNT { get; set; }
    }
}
