//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public SERVICE()
        {
            this.BASE_METER_SPEC = new HashSet<BASE_METER_SPEC>();
            this.METER_SPEC = new HashSet<METER_SPEC>();
            this.REQUEST_ROW = new HashSet<REQUEST_ROW>();
            this.BILL = new HashSet<BILL>();
            this.SAS_PUBLIC = new HashSet<SAS_PUBLIC>();
            this.SERVICE_TARIFF = new HashSet<SERVICE_TARIFF>();
            this.BIL_DEBIT = new HashSet<BIL_DEBIT>();
            this.BIL_ACCOUNT = new HashSet<BIL_ACCOUNT>();
        }
    
        public int FILE_NO { get; set; }
        public string REGN_CODE { get; set; }
        public short CTRL_DIGT { get; set; }
        public string CYCL_STAT { get; set; }
        public string CUST_STAT { get; set; }
        public string ONOF_TAG { get; set; }
        public string READ_STAT { get; set; }
        public short CLSD_NUMB { get; set; }
        public string CONF_STAT { get; set; }
        public string SALE_TYPE { get; set; }
        public Nullable<System.DateTime> LAST_READ_DATE { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string SERV_TYPE_DNRM { get; set; }
        public string SERV_NO_DNRM { get; set; }
        public string YEAR_DNRM { get; set; }
        public string CYCL_DNRM { get; set; }
        public Nullable<short> LAST_BILL_DNRM { get; set; }
        public Nullable<long> DEBT_DNRM { get; set; }
        public Nullable<int> EFCT_RQID_DNRM { get; set; }
        public Nullable<short> EFCT_RQNO_DNRM { get; set; }
        public Nullable<short> EFCT_RQST_TYPE_DNRM { get; set; }
        public string EFCT_REGN_CODE_DNRM { get; set; }
        public string EFCT_CYCL_DNRM { get; set; }
        public Nullable<int> MNTC_COST_DNRM { get; set; }
        public Nullable<System.DateTime> CONF_DATE { get; set; }
        public string TEMP_BRNC { get; set; }
        public Nullable<System.DateTime> TEMP_END_DATE_DNRM { get; set; }
        public string POWR_DECR { get; set; }
        public Nullable<System.DateTime> DECR_END_DATE_DNRM { get; set; }
        public Nullable<short> BASE_SEQ_DNRM { get; set; }
        public Nullable<short> METR_SEQ_DNRM { get; set; }
        public Nullable<short> PBLC_SEQ_DNRM { get; set; }
        public Nullable<short> TARF_SEQ_DNRM { get; set; }
        public string TARF_CODE_DNRM { get; set; }
        public string NAME_DNRM { get; set; }
        public string SERV_ADDR_DNRM { get; set; }
        public string ID_CODE_DNRM { get; set; }
        public string ZONE_CODE_DNRM { get; set; }
        public string ZIP_CODE_DNRM { get; set; }
        public Nullable<short> FMLY_NUMB_DNRM { get; set; }
        public string RISK_CODE_DNRM { get; set; }
        public string HSPL_CODE_DNRM { get; set; }
        public string ITEM_CODE { get; set; }
        public string POWR_CODE { get; set; }
        public string DLVR_VOLT { get; set; }
        public string BRNC_TYPE_DNRM { get; set; }
        public string CONS_CODE_DNRM { get; set; }
        public Nullable<short> CTGY_CODE_DNRM { get; set; }
        public Nullable<short> WORK_TYPE_DNRM { get; set; }
        public string PHAS_DNRM { get; set; }
        public Nullable<int> AMPR_DNRM { get; set; }
        public Nullable<decimal> CNTR_DMND_DNRM { get; set; }
        public Nullable<System.DateTime> INST_DATE_DNRM { get; set; }
        public string WORK_DAY_DNRM { get; set; }
        public string BLOK_DNRM { get; set; }
        public string SEQ_DNRM { get; set; }
        public Nullable<int> MAST_FILE_NO { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public string ORGN_DNRM { get; set; }
        public string BILL_IDNT { get; set; }
        public string METR_TAG { get; set; }
        public string SHAD_CODE_DNRM { get; set; }
        public string METR_STAT { get; set; }
    
        public virtual ICollection<BASE_METER_SPEC> BASE_METER_SPEC { get; set; }
        public virtual ICollection<METER_SPEC> METER_SPEC { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual ICollection<REQUEST_ROW> REQUEST_ROW { get; set; }
        public virtual ICollection<BILL> BILL { get; set; }
        public virtual ICollection<SAS_PUBLIC> SAS_PUBLIC { get; set; }
        public virtual ICollection<SERVICE_TARIFF> SERVICE_TARIFF { get; set; }
        public virtual ICollection<BIL_DEBIT> BIL_DEBIT { get; set; }
        public virtual ICollection<BIL_ACCOUNT> BIL_ACCOUNT { get; set; }
    }
}
