//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Emis.Sas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEP_HISTORY_SUMMERY
    {
        public STEP_HISTORY_SUMMERY()
        {
            this.STEP_HISTORY_DETAIL = new HashSet<STEP_HISTORY_DETAIL>();
        }
    
        public int RQST_RQID { get; set; }
        public short ROW_NO { get; set; }
        public short MAIN_STAT { get; set; }
        public string ARCH_STAT { get; set; }
        public string TRAN_STAT { get; set; }
        public string CRET_BY { get; set; }
        public System.DateTime CRET_DATE { get; set; }
        public string MDFY_BY { get; set; }
        public Nullable<System.DateTime> MDFY_DATE { get; set; }
        public Nullable<short> RESN_RQTP_CODE { get; set; }
        public Nullable<short> RESN_RWNO { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string SHIS_DESC { get; set; }
        public string ADMN_BTCH { get; set; }
    
        public virtual REQUEST REQUEST { get; set; }
        public virtual ICollection<STEP_HISTORY_DETAIL> STEP_HISTORY_DETAIL { get; set; }
    }
}
